### ISSUE TITLE
I want to join your team

### ISSUE THREAD

**Issue by kentaurse** [instructor-ai/instructor-rs#11]
hello team
As a seasoned web full-stack and blockchain developer, I specialize in crafting robust, user-centric web applications and implementing secure, decentralized solutions using the latest technologies and frameworks.

**Comment by technyk** [comment]
> Beware, this user appears to be a fake account. They have been asking various orgs (including an org I'm in via Discord) for full access without any real reasoning, and their GitHub appears to be bot driven. Some other examples of access requests with little-to-no reasoning:
> 
> 1. [Invite me your team collective.inviting#2](https://github.com/collective/collective.inviting/issues/2)
> 2. [Please add me to the collective #1868](https://github.com/collective/Collective/issues/1868)
> 3. [I want to join this oganization jenkinsci/multibranch-action-triggers-plugin#30](https://github.com/jenkinsci/multibranch-action-triggers-plugin/issues/30)
> 4. [I want to join your team kimurayu45z/ng-algoliasearch#28](https://github.com/kimurayu45z/ng-algoliasearch/issues/28)
> 
> Most of their repos are forks / fake re-uploads, e.g.https://github.com/kentaurse/blockchain-tutorial which is a clone of https://github.com/nosequeldeebee/blockchain-tutorial but with the git history re-written to make it seem like they authored it.
